// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type DayCompleted struct {
	ID        int64     `json:"id"`
	HabitID   int64     `json:"habit_id"`
	Date      string    `json:"date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Event struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	// Single| Monthly | Annualy | Weekly
	Frequency          string       `json:"frequency"`
	BeginTime          string       `json:"begin_time"`
	EndTime            string       `json:"end_time"`
	UserID             int64        `json:"user_id"`
	CreatedAt          sql.NullTime `json:"created_at"`
	UpdatedAt          sql.NullTime `json:"updated_at"`
	FrequencyExtension string       `json:"frequency_extension"`
}

type Habit struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Streak    int64        `json:"streak"`
	WeekDays  string       `json:"week_days"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Todo struct {
	ID        int64        `json:"id"`
	Title     string       `json:"title"`
	Term      string       `json:"term"`
	Completed bool         `json:"completed"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	UserID    int64        `json:"user_id"`
}

type User struct {
	ID        int64        `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
