// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CompleteDay(ctx context.Context, arg CompleteDayParams) (DayCompleted, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCompletedDay(ctx context.Context, arg DeleteCompletedDayParams) (DayCompleted, error)
	DeleteTodo(ctx context.Context, id int64) (Todo, error)
	GetHabit(ctx context.Context, id int64) (Habit, error)
	GetTodo(ctx context.Context, id int64) (Todo, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListCompletedDays(ctx context.Context, habitID int64) ([]DayCompleted, error)
	ListEventByUser(ctx context.Context, userID int64) ([]Event, error)
	ListHabits(ctx context.Context, userID int64) ([]Habit, error)
	ListTodoByUser(ctx context.Context, userID int64) ([]Todo, error)
	ToggleTodo(ctx context.Context, id int64) (Todo, error)
}

var _ Querier = (*Queries)(nil)
