// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, id int64) (Todo, error)
	GetTodo(ctx context.Context, id int64) (Todo, error)
	GetUser(ctx context.Context, email string) (User, error)
	ListEventByUser(ctx context.Context, userID int64) ([]Event, error)
	ListTodoByUser(ctx context.Context, userID int64) ([]Todo, error)
	ToggleTodo(ctx context.Context, id int64) (Todo, error)
}

var _ Querier = (*Queries)(nil)
